# application.yml : ?????? ?? ??? ???? ?? ???????? ???? ?? ??
# ?? application.properties? ???, ??????? ??? ? properties? ???? ??(?????? properties ???? ??)

server:
  # ?? ?? ?? ??
  port: 8080
  servlet:
    # ? ???????? ?? ??? ??
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohgiraffers_db?serverTimezone=Asia/Seoul
    hikari:
      username: ohgiraffers
      password: ohgiraffers

# JPA/Hibernate ??
# Hibernate : JPA? ???. ?? ??? ?????? ??? ??? ????? ORM
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      show_sql: true

